#!/usr/bin/env bash
# gen_webui_gzip_header.sh
# Compress webui/index.html, webui/wifi.html, webui/audio.html, webui/system.html,
# and webui/onboarding.html, then emit include/WebUI_gz.h.
# Usage: bash tools/gen_webui_gzip_header.sh   (run from project root)
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INDEX_HTML="${ROOT_DIR}/webui/index.html"
WIFI_HTML="${ROOT_DIR}/webui/wifi.html"
AUDIO_HTML="${ROOT_DIR}/webui/audio.html"
SYSTEM_HTML="${ROOT_DIR}/webui/system.html"
ONBOARDING_HTML="${ROOT_DIR}/webui/onboarding.html"
OUT_FILE="${ROOT_DIR}/include/WebUI_gz.h"

for f in "${INDEX_HTML}" "${WIFI_HTML}" "${AUDIO_HTML}" "${SYSTEM_HTML}" "${ONBOARDING_HTML}"; do
  if [[ ! -f "${f}" ]]; then
    echo "Missing HTML source: ${f}" >&2
    exit 1
  fi
done

command -v gzip  >/dev/null 2>&1 || { echo "gzip not found" >&2; exit 1; }
command -v xxd   >/dev/null 2>&1 || { echo "xxd not found"  >&2; exit 1; }

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

emit_array() {
  local html_file="$1"
  local symbol="$2"
  local gz_file="${TMP_DIR}/${symbol}.gz"

  # -n: no filename/timestamp in header (deterministic output)
  # -9: max compression
  gzip -n -9 -c "${html_file}" > "${gz_file}"
  local gz_len
  gz_len="$(wc -c < "${gz_file}" | tr -d ' ')"

  echo "// Source: ${html_file#${ROOT_DIR}/}"
  echo "static const uint8_t ${symbol}_GZ[] PROGMEM = {"
  # xxd -i prints a C-array body; strip declaration and closing/size lines.
  xxd -i "${gz_file}" | tail -n +2 | awk 'NR>2{print buf[NR%2]} {buf[NR%2]=$0}'
  echo "};"
  echo ""
  echo "static const size_t ${symbol}_GZ_LEN = ${gz_len};"
  echo ""
}

{
  echo "#pragma once"
  echo "// Auto-generated by tools/gen_webui_gzip_header.sh — do not edit manually."
  echo "#include <Arduino.h>"
  echo "#include <pgmspace.h>"
  echo ""
  emit_array "${INDEX_HTML}" "WEBUI_INDEX"
  emit_array "${WIFI_HTML}" "WEBUI_WIFI"
  emit_array "${AUDIO_HTML}" "WEBUI_AUDIO"
  emit_array "${SYSTEM_HTML}" "WEBUI_SYSTEM"
  emit_array "${ONBOARDING_HTML}" "WEBUI_ONBOARDING"
} > "${OUT_FILE}"

INDEX_LEN="$(gzip -n -9 -c "${INDEX_HTML}" | wc -c | tr -d ' ')"
WIFI_LEN="$(gzip -n -9 -c "${WIFI_HTML}" | wc -c | tr -d ' ')"
AUDIO_LEN="$(gzip -n -9 -c "${AUDIO_HTML}" | wc -c | tr -d ' ')"
SYSTEM_LEN="$(gzip -n -9 -c "${SYSTEM_HTML}" | wc -c | tr -d ' ')"
ONBOARDING_LEN="$(gzip -n -9 -c "${ONBOARDING_HTML}" | wc -c | tr -d ' ')"
echo "Generated ${OUT_FILE} (index ${INDEX_LEN} bytes, wifi ${WIFI_LEN} bytes, audio ${AUDIO_LEN} bytes, system ${SYSTEM_LEN} bytes, onboarding ${ONBOARDING_LEN} bytes gzipped)"
