#!/usr/bin/env bash
# gen_webui_gzip_header.sh
# Compress webui/index.html and emit include/WebUI_gz.h as a PROGMEM byte array.
# Usage: bash tools/gen_webui_gzip_header.sh   (run from project root)
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HTML_FILE="${ROOT_DIR}/webui/index.html"
OUT_FILE="${ROOT_DIR}/include/WebUI_gz.h"

if [[ ! -f "${HTML_FILE}" ]]; then
  echo "Missing HTML source: ${HTML_FILE}" >&2
  exit 1
fi

command -v gzip  >/dev/null 2>&1 || { echo "gzip not found" >&2; exit 1; }
command -v xxd   >/dev/null 2>&1 || { echo "xxd not found"  >&2; exit 1; }

TMP_GZ="$(mktemp)"
trap 'rm -f "${TMP_GZ}"' EXIT

# -n: no filename/timestamp in header (deterministic output)
# -9: max compression
gzip -n -9 -c "${HTML_FILE}" > "${TMP_GZ}"
GZ_LEN="$(wc -c < "${TMP_GZ}" | tr -d ' ')"

{
  echo "#pragma once"
  echo "// Auto-generated by tools/gen_webui_gzip_header.sh — do not edit manually."
  echo "// Source: webui/index.html"
  echo "#include <Arduino.h>"
  echo "#include <pgmspace.h>"
  echo ""
  echo "static const uint8_t WEBUI_INDEX_GZ[] PROGMEM = {"
  # xxd -i prints a C-array body; strip the first and last two lines (variable declaration / closing brace + size)
  # Strip xxd's first line (variable declaration) and last two lines (closing brace + size var).
  # Portable: tail for the leading skip, awk sliding-window to drop last 2 lines.
  xxd -i "${TMP_GZ}" | tail -n +2 | awk 'NR>2{print buf[NR%2]} {buf[NR%2]=$0}'
  echo "};"
  echo ""
  echo "static const size_t WEBUI_INDEX_GZ_LEN = ${GZ_LEN};"
} > "${OUT_FILE}"

echo "Generated ${OUT_FILE} (${GZ_LEN} bytes gzipped)"
